### ISSUE TITLE
meshctl binary panics because of dependency on skv2/contrib

### ISSUE THREAD

**Issue by harveyxia** [solo-io/service-mesh-hub#887]
```
panic: stat /go/pkg/mod/github.com/solo-io/skv2@v0.9.0/contrib/codegen/templates/sets/sets.gotmpl: no such file or directory

goroutine 1 [running]:
github.com/solo-io/skv2/contrib.glob..func1(0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/skv2@v0.9.0/contrib/custom_group_templates.go:30 +0x369
github.com/solo-io/skv2/contrib.init()
	/go/pkg/mod/github.com/solo-io/skv2@v0.9.0/contrib/custom_group_templates.go:39 +0x73
```

Our `meshctl` transitively imports `github.com/solo-io/skv2/tree/master/contrib` which panics if `sets.gotmpl` isn't found. Because that file isn't packed, it will panic. The fix is to remove all transitive references to the offending package.

**Comment by joekelley** [comment]
fixed in 0.7.1
