### ISSUE TITLE
Make targets broken for meshctl

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/service-mesh-hub#978]
```
make install-cli
packr build -ldflags="-X github.com/solo-io/service-mesh-hub/pkg/common/version.Version=0.7.5-9-gffe79d60" -gcflags=all="-N -l" -o /Users/ashwang/go/bin/meshctl cmd/meshctl/main.go
➜  service-mesh-hub git:(main) meshctl --version
panic: stat /Users/ashwang/go/pkg/mod/github.com/solo-io/skv2@v0.8.2-0.20200814160410-397370b8b828/contrib/codegen/templates/sets/sets.gotmpl: no such file or directory

goroutine 1 [running]:
github.com/solo-io/skv2/contrib.glob..func1(0x0, 0x0, 0x0)
	/Users/ashwang/go/pkg/mod/github.com/solo-io/skv2@v0.8.2-0.20200814160410-397370b8b828/contrib/custom_group_templates.go:30 +0x369
github.com/solo-io/skv2/contrib.init()
	/Users/ashwang/go/pkg/mod/github.com/solo-io/skv2@v0.8.2-0.20200814160410-397370b8b828/contrib/custom_group_templates.go:39 +0x73
```

**Comment by ashleywang1** [comment]
Unable to reproduce - must've been something wrong in my environment.
